2022-09-12 22:13:54,945 INFO: Microblog startup [in /home/kinchu/Projects/flask_mega_book/app/__init__.py:53]
2022-09-12 22:21:01,025 INFO: Microblog startup [in /home/kinchu/Projects/flask_mega_book/app/__init__.py:53]
2022-09-12 22:26:05,252 INFO: Microblog startup [in /home/kinchu/Projects/flask_mega_book/app/__init__.py:53]
2022-09-12 22:26:10,154 ERROR: Exception on /index [GET] [in /home/kinchu/.local/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/kinchu/Projects/flask_mega_book/app/routes.py", line 27, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2022-09-12 22:26:11,668 ERROR: Exception on /index [GET] [in /home/kinchu/.local/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/kinchu/Projects/flask_mega_book/app/routes.py", line 27, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2022-09-12 22:26:13,032 ERROR: Exception on /explore [GET] [in /home/kinchu/.local/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/kinchu/Projects/flask_mega_book/app/routes.py", line 27, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2022-09-12 22:26:13,960 ERROR: Exception on /index [GET] [in /home/kinchu/.local/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/kinchu/Projects/flask_mega_book/app/routes.py", line 27, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2022-09-12 22:26:15,381 ERROR: Exception on /index [GET] [in /home/kinchu/.local/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/kinchu/Projects/flask_mega_book/app/routes.py", line 27, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2022-09-12 22:26:16,207 ERROR: Exception on /index [GET] [in /home/kinchu/.local/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/kinchu/Projects/flask_mega_book/app/routes.py", line 27, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2022-09-12 22:26:16,982 ERROR: Exception on /index [GET] [in /home/kinchu/.local/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/kinchu/.local/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/kinchu/Projects/flask_mega_book/app/routes.py", line 27, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2022-09-12 22:27:08,093 INFO: Microblog startup [in /home/kinchu/Projects/flask_mega_book/app/__init__.py:53]
2022-09-12 22:28:47,822 INFO: Microblog startup [in /home/kinchu/Projects/flask_mega_book/app/__init__.py:52]
